<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>FlatOut4SaveEditorSetup</AssemblyName>
    <RootNamespace>FlatOut4SaveEditorLauncher</RootNamespace>

    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\FlatOut4SaveEditor.zip"
                      Condition="Exists('Resources\FlatOut4SaveEditor.zip')"
                      LogicalName="FlatOut4SaveEditor.zip" />
  </ItemGroup>

</Project>
